// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://swagger.json` | (string & {});
};

export type AddHwidRequest = {
    hwid?: string | null;
};

export type AddTicketCommentRequest = {
    content?: string | null;
};

export type AdminMigrateLicenseRequest = {
    newHwid?: string | null;
    reason?: string | null;
    overrideLimit?: boolean;
};

export type AppUserDto = {
    userId?: string | null;
    email?: string | null;
    roles?: Array<string> | null;
    claims?: Array<Claim> | null;
    city?: string | null;
    phoneNumber?: string | null;
};

export type AppUserDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<AppUserDto> | null;
    readonly errors?: Array<Error> | null;
};

export type AppUserDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: AppUserDto;
    readonly errors?: Array<Error> | null;
};

export type Claim = {
    readonly issuer?: string | null;
    readonly originalIssuer?: string | null;
    readonly properties?: {
        [key: string]: string;
    } | null;
    subject?: ClaimsIdentity;
    readonly type?: string | null;
    readonly value?: string | null;
    readonly valueType?: string | null;
};

export type ClaimsIdentity = {
    readonly authenticationType?: string | null;
    readonly isAuthenticated?: boolean;
    actor?: ClaimsIdentity;
    bootstrapContext?: unknown;
    readonly claims?: Array<Claim> | null;
    label?: string | null;
    readonly name?: string | null;
    readonly nameClaimType?: string | null;
    readonly roleClaimType?: string | null;
};

export type CreateChildProductRequest = {
    name?: string | null;
    fullName?: string | null;
    family?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    allowTrial?: boolean;
    trialPeriod?: number | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    expiryDate?: string | null;
    prices?: Array<ProductPriceRequest> | null;
};

export type CreateLicenseCommand = {
    userId?: string;
    productId?: string;
    name?: string | null;
    email?: string | null;
    licenseCount?: number;
    migrationLimit?: number;
    expiryDate?: string | null;
    isTrial?: boolean;
    willExpire?: boolean;
    type?: string | null;
};

export type CreateProductCommand = {
    name?: string | null;
    fullName?: string | null;
    family?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    allowTrial?: boolean;
    trialPeriod?: number | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    expiryDate?: string | null;
    prices?: Array<ProductPriceRequest> | null;
    media?: Array<ProductMediaRequest> | null;
};

export type CreatePromocodeCommand = {
    code?: string | null;
};

export type CreateTicketCategoryCommand = {
    name?: string | null;
};

export type CreateTicketRequest = {
    title?: string | null;
    description?: string | null;
    categoryId?: string | null;
    priority?: string | null;
};

export type Deleted = {
    [key: string]: never;
};

export type DeletedResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: Deleted;
    readonly errors?: Array<Error> | null;
};

export type Error = {
    readonly code?: string | null;
    readonly description?: string | null;
    type?: ErrorKind;
};

export type ErrorKind = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type GetLicenseDiagnosticResponse = {
    id?: string;
    serial?: string | null;
    janDrozdId?: string | null;
    provider?: string | null;
    isActive?: boolean;
    willExpire?: boolean;
    expiryDate?: string | null;
    licenseCount?: number;
    migrationLimit?: number;
    isTrial?: boolean;
    type?: string | null;
    version?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
    customer?: unknown;
    product?: unknown;
    hardwareIds?: unknown;
    stats?: unknown;
};

export type GetLicenseDiagnosticResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: GetLicenseDiagnosticResponse;
    readonly errors?: Array<Error> | null;
};

export type GetLicenseHwidsResponse = {
    hwids?: Array<string> | null;
    source?: string | null;
    customerId?: string | null;
};

export type GetLicenseHwidsResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: GetLicenseHwidsResponse;
    readonly errors?: Array<Error> | null;
};

export type GoogleLoginRequest = {
    idToken?: string | null;
};

export type LicenseClientDto = {
    id?: string;
    userId?: string;
    productId?: string;
    hwid?: string | null;
    deviceName?: string | null;
    lastUsedAt?: string | null;
    resetCount?: number;
    lastResetAt?: string | null;
    isActive?: boolean;
};

export type LicenseDto = {
    id?: string;
    userId?: string;
    productId?: string;
    paymentId?: string | null;
    pendingLicenseId?: string | null;
    licenseCount?: number;
    migrationLimit?: number;
    name?: string | null;
    email?: string | null;
    hwidSalt?: string | null;
    willExpire?: boolean;
    expiryDate?: string | null;
    serial?: string | null;
    janDrozdId?: string | null;
    isTrial?: boolean;
    type?: string | null;
    version?: string | null;
    addedBy?: string | null;
    addedByName?: string | null;
    productName?: string | null;
    isActive?: boolean;
    source?: string | null;
    provider?: string | null;
    createdAtUtc?: string;
    clients?: Array<LicenseClientDto> | null;
};

export type LicenseDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<LicenseDto> | null;
    readonly errors?: Array<Error> | null;
};

export type LicenseDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: LicenseDto;
    readonly errors?: Array<Error> | null;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ObjectResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: unknown;
    readonly errors?: Array<Error> | null;
};

export type PayablePriceDto = {
    id?: string;
    country?: string | null;
    price?: number;
    period?: number | null;
    active?: boolean;
};

export type PaymentBillingData = {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    apartment?: string | null;
    floor?: string | null;
    street?: string | null;
    building?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    postalCode?: string | null;
};

export type PaymentCheckoutSessionRequest = {
    resourceId: string;
    referenceCode: string;
    amountInMinorUnits?: number;
    currency: string;
    paymentMethodIntegrationIds?: Array<number> | null;
    billingData: PaymentBillingData;
    items?: Array<PaymentItem> | null;
    notificationUrl?: string | null;
    redirectionUrl?: string | null;
    extras?: {
        [key: string]: string;
    } | null;
};

export type PaymentCheckoutSessionResponse = {
    intentionId?: string | null;
    clientSecret?: string | null;
    publicKey?: string | null;
    paymentPageUrl?: string | null;
};

export type PaymentCheckoutSessionResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PaymentCheckoutSessionResponse;
    readonly errors?: Array<Error> | null;
};

export type PaymentItem = {
    name?: string | null;
    description?: string | null;
    amountInMinorUnits?: number;
    quantity?: number;
};

export type PaymentWebhookParseResult = {
    isValid?: boolean;
    referenceCode?: string | null;
    externalTransactionId?: string | null;
    isSuccessfulPayment?: boolean;
    isFailure?: boolean;
    failureReason?: string | null;
    eventType?: string | null;
};

export type PaymentWebhookParseResultResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PaymentWebhookParseResult;
    readonly errors?: Array<Error> | null;
};

export type ProductDto = {
    id?: string;
    name?: string | null;
    fullName?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    family?: string | null;
    parentProductId?: string | null;
    allowTrial?: boolean;
    trialPeriod?: number | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    expiryDate?: string | null;
    createdAtUtc?: string;
    createdBy?: string | null;
    lastModifiedUtc?: string;
    lastModifiedBy?: string | null;
    prices?: Array<PayablePriceDto> | null;
    children?: Array<ProductDto> | null;
    media?: Array<ProductMediaDto> | null;
    features?: Array<ProductFeatureDto> | null;
};

export type ProductDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<ProductDto> | null;
    readonly errors?: Array<Error> | null;
};

export type ProductDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductDto;
    readonly errors?: Array<Error> | null;
};

export type ProductFeatureDto = {
    id?: string;
    productId?: string;
    featureName?: string | null;
    featureType?: string | null;
    janDrozdFeatureId?: string | null;
    createdAtUtc?: string;
    createdBy?: string | null;
    lastModifiedUtc?: string;
    lastModifiedBy?: string | null;
};

export type ProductFeatureDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductFeatureDto;
    readonly errors?: Array<Error> | null;
};

export type ProductFeatureRequest = {
    featureName?: string | null;
    featureType?: string | null;
    janDrozdFeatureId?: string | null;
};

export type ProductMediaDto = {
    id?: string;
    productId?: string;
    url?: string | null;
    order?: number;
};

export type ProductMediaDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductMediaDto;
    readonly errors?: Array<Error> | null;
};

export type ProductMediaRequest = {
    url?: string | null;
    order?: number;
};

export type ProductPriceRequest = {
    country?: string | null;
    price?: number;
    period?: number | null;
    active?: boolean;
};

export type PromocodeDto = {
    id?: string;
    code?: string | null;
    defaultPriceMultiplier?: number | null;
    fixedDiscount?: number | null;
    constantDiscount?: number | null;
    hidden?: boolean;
    withTaxes?: boolean;
    expiresAt?: string | null;
    maxUses?: number | null;
    useCount?: number;
};

export type PromocodeDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<PromocodeDto> | null;
    readonly errors?: Array<Error> | null;
};

export type PromocodeDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PromocodeDto;
    readonly errors?: Array<Error> | null;
};

export type RefreshTokenRequest = {
    accessToken: string;
    refreshToken: string;
};

export type RegisterUserRequest = {
    email: string;
    password: string;
    role: string;
    city?: string | null;
    phoneNumber?: string | null;
};

export type RenewLicenseRequest = {
    period?: number;
};

export type ResetLicenseHwidRequest = {
    reason?: string | null;
};

export type RestoreDeletedUserRequest = {
    email: string;
    password: string;
};

export type StringIReadOnlyCollectionResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<string> | null;
    readonly errors?: Array<Error> | null;
};

export type StringListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<string> | null;
    readonly errors?: Array<Error> | null;
};

export type TicketCategoryDto = {
    id?: string;
    name?: string | null;
    description?: string | null;
    order?: number;
    isActive?: boolean;
};

export type TokenResponse = {
    accessToken?: string | null;
    refreshToken?: string | null;
    expiresOnUtc?: string;
};

export type TokenResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: TokenResponse;
    readonly errors?: Array<Error> | null;
};

export type UpdateLicenseCommand = {
    id?: string;
    licenseCount?: number;
    migrationLimit?: number;
    expiryDate?: string | null;
    isTrial?: boolean;
    isActive?: boolean;
    serial?: string | null;
    janDrozdId?: string | null;
};

export type UpdateProductCommand = {
    id?: string;
    name?: string | null;
    fullName?: string | null;
    family?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    parentProductId?: string | null;
    allowTrial?: boolean;
    trialPeriod?: number | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    expiryDate?: string | null;
    prices?: Array<ProductPriceRequest> | null;
    media?: Array<ProductMediaRequest> | null;
};

export type UpdatePromocodeAudienceCommand = {
    id?: string;
    hidden?: boolean;
    withTaxes?: boolean;
};

export type UpdatePromocodeDiscountsCommand = {
    id?: string;
    defaultPriceMultiplier?: number | null;
    fixedDiscount?: number | null;
    constantDiscount?: number | null;
    expiresAt?: string | null;
    maxUses?: number | null;
};

export type UpdateTicketCategoryCommand = {
    id?: string;
    name?: string | null;
    description?: string | null;
    order?: number;
    isActive?: boolean;
};

export type UpdateTicketStatusRequest = {
    status?: string | null;
};

export type Updated = {
    [key: string]: never;
};

export type UpdatedResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: Updated;
    readonly errors?: Array<Error> | null;
};

export type AppUserDtoWritable = {
    userId?: string | null;
    email?: string | null;
    roles?: Array<string> | null;
    claims?: Array<ClaimWritable> | null;
    city?: string | null;
    phoneNumber?: string | null;
};

export type AppUserDtoListResultWritable = {
    [key: string]: never;
};

export type AppUserDtoResultWritable = {
    value?: AppUserDtoWritable;
};

export type ClaimWritable = {
    subject?: ClaimsIdentityWritable;
};

export type ClaimsIdentityWritable = {
    actor?: ClaimsIdentityWritable;
    bootstrapContext?: unknown;
    label?: string | null;
};

export type DeletedResultWritable = {
    value?: Deleted;
};

export type ErrorWritable = {
    type?: ErrorKind;
};

export type GetLicenseDiagnosticResponseResultWritable = {
    value?: GetLicenseDiagnosticResponse;
};

export type GetLicenseHwidsResponseResultWritable = {
    value?: GetLicenseHwidsResponse;
};

export type LicenseDtoListResultWritable = {
    [key: string]: never;
};

export type LicenseDtoResultWritable = {
    value?: LicenseDto;
};

export type ObjectResultWritable = {
    [key: string]: never;
};

export type PaymentCheckoutSessionResponseResultWritable = {
    value?: PaymentCheckoutSessionResponse;
};

export type PaymentWebhookParseResultResultWritable = {
    value?: PaymentWebhookParseResult;
};

export type ProductDtoListResultWritable = {
    [key: string]: never;
};

export type ProductDtoResultWritable = {
    value?: ProductDto;
};

export type ProductFeatureDtoResultWritable = {
    value?: ProductFeatureDto;
};

export type ProductMediaDtoResultWritable = {
    value?: ProductMediaDto;
};

export type PromocodeDtoListResultWritable = {
    [key: string]: never;
};

export type PromocodeDtoResultWritable = {
    value?: PromocodeDto;
};

export type StringIReadOnlyCollectionResultWritable = {
    [key: string]: never;
};

export type StringListResultWritable = {
    [key: string]: never;
};

export type TokenResponseResultWritable = {
    value?: TokenResponse;
};

export type UpdatedResultWritable = {
    value?: Updated;
};

export type PostIdentitySignupData = {
    /**
     * The registration details (email, password, etc.).
     */
    body?: RegisterUserRequest;
    path?: never;
    query?: never;
    url: '/identity/signup';
};

export type PostIdentitySignupErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PostIdentitySignupError = PostIdentitySignupErrors[keyof PostIdentitySignupErrors];

export type PostIdentitySignupResponses = {
    /**
     * Created
     */
    201: TokenResponseResult;
};

export type PostIdentitySignupResponse = PostIdentitySignupResponses[keyof PostIdentitySignupResponses];

export type PostIdentityTokenGenerateData = {
    /**
     * The login credentials.
     */
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/identity/token/generate';
};

export type PostIdentityTokenGenerateErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityTokenGenerateError = PostIdentityTokenGenerateErrors[keyof PostIdentityTokenGenerateErrors];

export type PostIdentityTokenGenerateResponses = {
    /**
     * OK
     */
    200: TokenResponseResult;
};

export type PostIdentityTokenGenerateResponse = PostIdentityTokenGenerateResponses[keyof PostIdentityTokenGenerateResponses];

export type PostIdentityTokenGoogleData = {
    /**
     * The Google login credentials containing the IdToken.
     */
    body?: GoogleLoginRequest;
    path?: never;
    query?: never;
    url: '/identity/token/google';
};

export type PostIdentityTokenGoogleErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityTokenGoogleError = PostIdentityTokenGoogleErrors[keyof PostIdentityTokenGoogleErrors];

export type PostIdentityTokenGoogleResponses = {
    /**
     * OK
     */
    200: TokenResponseResult;
};

export type PostIdentityTokenGoogleResponse = PostIdentityTokenGoogleResponses[keyof PostIdentityTokenGoogleResponses];

export type PostIdentityTokenRefreshTokenData = {
    /**
     * The access and refresh tokens.
     */
    body?: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/identity/token/refresh-token';
};

export type PostIdentityTokenRefreshTokenErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityTokenRefreshTokenError = PostIdentityTokenRefreshTokenErrors[keyof PostIdentityTokenRefreshTokenErrors];

export type PostIdentityTokenRefreshTokenResponses = {
    /**
     * OK
     */
    200: TokenResponseResult;
};

export type PostIdentityTokenRefreshTokenResponse = PostIdentityTokenRefreshTokenResponses[keyof PostIdentityTokenRefreshTokenResponses];

export type PostIdentityRestoreDeletedUserData = {
    /**
     * The email and password of the user to restore.
     */
    body?: RestoreDeletedUserRequest;
    path?: never;
    query?: never;
    url: '/identity/restore-deleted-user';
};

export type PostIdentityRestoreDeletedUserErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityRestoreDeletedUserError = PostIdentityRestoreDeletedUserErrors[keyof PostIdentityRestoreDeletedUserErrors];

export type PostIdentityRestoreDeletedUserResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PostIdentityRestoreDeletedUserResponse = PostIdentityRestoreDeletedUserResponses[keyof PostIdentityRestoreDeletedUserResponses];

export type GetIdentityUsersByUserIdPermissionsData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/users/{userId}/permissions';
};

export type GetIdentityUsersByUserIdPermissionsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetIdentityUsersByUserIdPermissionsError = GetIdentityUsersByUserIdPermissionsErrors[keyof GetIdentityUsersByUserIdPermissionsErrors];

export type GetIdentityUsersByUserIdPermissionsResponses = {
    /**
     * OK
     */
    200: StringListResult;
};

export type GetIdentityUsersByUserIdPermissionsResponse = GetIdentityUsersByUserIdPermissionsResponses[keyof GetIdentityUsersByUserIdPermissionsResponses];

export type PutIdentityUsersByUserIdPermissionsData = {
    /**
     * The list of permission strings to assign.
     */
    body?: Array<string>;
    path: {
        /**
         * The unique identifier of the user.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/users/{userId}/permissions';
};

export type PutIdentityUsersByUserIdPermissionsErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutIdentityUsersByUserIdPermissionsError = PutIdentityUsersByUserIdPermissionsErrors[keyof PutIdentityUsersByUserIdPermissionsErrors];

export type PutIdentityUsersByUserIdPermissionsResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutIdentityUsersByUserIdPermissionsResponse = PutIdentityUsersByUserIdPermissionsResponses[keyof PutIdentityUsersByUserIdPermissionsResponses];

export type GetIdentityMyPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/my-permissions';
};

export type GetIdentityMyPermissionsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type GetIdentityMyPermissionsError = GetIdentityMyPermissionsErrors[keyof GetIdentityMyPermissionsErrors];

export type GetIdentityMyPermissionsResponses = {
    /**
     * OK
     */
    200: StringListResult;
};

export type GetIdentityMyPermissionsResponse = GetIdentityMyPermissionsResponses[keyof GetIdentityMyPermissionsResponses];

export type GetIdentityAllPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/all-permissions';
};

export type GetIdentityAllPermissionsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityAllPermissionsError = GetIdentityAllPermissionsErrors[keyof GetIdentityAllPermissionsErrors];

export type GetIdentityAllPermissionsResponses = {
    /**
     * OK
     */
    200: StringIReadOnlyCollectionResult;
};

export type GetIdentityAllPermissionsResponse = GetIdentityAllPermissionsResponses[keyof GetIdentityAllPermissionsResponses];

export type DeleteIdentityCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/current-user';
};

export type DeleteIdentityCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type DeleteIdentityCurrentUserError = DeleteIdentityCurrentUserErrors[keyof DeleteIdentityCurrentUserErrors];

export type DeleteIdentityCurrentUserResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteIdentityCurrentUserResponse = DeleteIdentityCurrentUserResponses[keyof DeleteIdentityCurrentUserResponses];

export type GetIdentityCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/current-user';
};

export type GetIdentityCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type GetIdentityCurrentUserError = GetIdentityCurrentUserErrors[keyof GetIdentityCurrentUserErrors];

export type GetIdentityCurrentUserResponses = {
    /**
     * OK
     */
    200: AppUserDtoResult;
};

export type GetIdentityCurrentUserResponse = GetIdentityCurrentUserResponses[keyof GetIdentityCurrentUserResponses];

export type GetIdentityUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/users';
};

export type GetIdentityUsersErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityUsersError = GetIdentityUsersErrors[keyof GetIdentityUsersErrors];

export type GetIdentityUsersResponses = {
    /**
     * OK
     */
    200: AppUserDtoListResult;
};

export type GetIdentityUsersResponse = GetIdentityUsersResponses[keyof GetIdentityUsersResponses];

export type GetIdentityUsersDeletedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/users/deleted';
};

export type GetIdentityUsersDeletedErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityUsersDeletedError = GetIdentityUsersDeletedErrors[keyof GetIdentityUsersDeletedErrors];

export type GetIdentityUsersDeletedResponses = {
    /**
     * OK
     */
    200: AppUserDtoListResult;
};

export type GetIdentityUsersDeletedResponse = GetIdentityUsersDeletedResponses[keyof GetIdentityUsersDeletedResponses];

export type DeleteIdentityByUserIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/{userId}';
};

export type DeleteIdentityByUserIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type DeleteIdentityByUserIdError = DeleteIdentityByUserIdErrors[keyof DeleteIdentityByUserIdErrors];

export type DeleteIdentityByUserIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteIdentityByUserIdResponse = DeleteIdentityByUserIdResponses[keyof DeleteIdentityByUserIdResponses];

export type GetApiLicensesData = {
    body?: never;
    path?: never;
    query?: {
        productId?: string;
        isActive?: boolean;
    };
    url: '/api/licenses';
};

export type GetApiLicensesResponses = {
    /**
     * OK
     */
    200: LicenseDtoListResult;
};

export type GetApiLicensesResponse = GetApiLicensesResponses[keyof GetApiLicensesResponses];

export type PostApiLicensesData = {
    body?: CreateLicenseCommand;
    path?: never;
    query?: never;
    url: '/api/licenses';
};

export type PostApiLicensesResponses = {
    /**
     * Created
     */
    201: LicenseDtoResult;
};

export type PostApiLicensesResponse = PostApiLicensesResponses[keyof PostApiLicensesResponses];

export type DeleteApiLicensesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}';
};

export type DeleteApiLicensesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiLicensesByIdResponse = DeleteApiLicensesByIdResponses[keyof DeleteApiLicensesByIdResponses];

export type GetApiLicensesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}';
};

export type GetApiLicensesByIdResponses = {
    /**
     * OK
     */
    200: LicenseDtoResult;
};

export type GetApiLicensesByIdResponse = GetApiLicensesByIdResponses[keyof GetApiLicensesByIdResponses];

export type PutApiLicensesByIdData = {
    body?: UpdateLicenseCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}';
};

export type PutApiLicensesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesClientsByClientIdResetData = {
    body?: ResetLicenseHwidRequest;
    path: {
        clientId: string;
    };
    query?: never;
    url: '/api/licenses/clients/{clientId}/reset';
};

export type PostApiLicensesClientsByClientIdResetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesAdminByIdMigrateData = {
    body?: AdminMigrateLicenseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/migrate';
};

export type PostApiLicensesAdminByIdMigrateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesByIdRenewData = {
    body?: RenewLicenseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}/renew';
};

export type PostApiLicensesByIdRenewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesAdminByIdRevokeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/revoke';
};

export type PostApiLicensesAdminByIdRevokeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLicensesAdminByIdHwidsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/hwids';
};

export type GetApiLicensesAdminByIdHwidsResponses = {
    /**
     * OK
     */
    200: GetLicenseHwidsResponseResult;
};

export type GetApiLicensesAdminByIdHwidsResponse = GetApiLicensesAdminByIdHwidsResponses[keyof GetApiLicensesAdminByIdHwidsResponses];

export type PostApiLicensesAdminByIdHwidsData = {
    body?: AddHwidRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/hwids';
};

export type PostApiLicensesAdminByIdHwidsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiLicensesAdminByIdHwidsByHwidData = {
    body?: never;
    path: {
        id: string;
        hwid: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/hwids/{hwid}';
};

export type DeleteApiLicensesAdminByIdHwidsByHwidResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLicensesAdminByIdDiagnosticData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/diagnostic';
};

export type GetApiLicensesAdminByIdDiagnosticResponses = {
    /**
     * OK
     */
    200: GetLicenseDiagnosticResponseResult;
};

export type GetApiLicensesAdminByIdDiagnosticResponse = GetApiLicensesAdminByIdDiagnosticResponses[keyof GetApiLicensesAdminByIdDiagnosticResponses];

export type PostApiPaymentsCheckoutData = {
    /**
     * The payment checkout details.
     */
    body?: PaymentCheckoutSessionRequest;
    path?: never;
    query?: never;
    url: '/api/payments/checkout';
};

export type PostApiPaymentsCheckoutErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Internal Server Error
     */
    500: ObjectResult;
};

export type PostApiPaymentsCheckoutError = PostApiPaymentsCheckoutErrors[keyof PostApiPaymentsCheckoutErrors];

export type PostApiPaymentsCheckoutResponses = {
    /**
     * OK
     */
    200: PaymentCheckoutSessionResponseResult;
};

export type PostApiPaymentsCheckoutResponse = PostApiPaymentsCheckoutResponses[keyof PostApiPaymentsCheckoutResponses];

export type PostApiPaymobWebhookData = {
    /**
     * The raw JSON payload from Paymob.
     */
    body?: unknown;
    path?: never;
    query?: {
        /**
         * The HMAC signature provided by Paymob in the query string.
         */
        hmac?: string;
    };
    url: '/api/paymob/webhook';
};

export type PostApiPaymobWebhookErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PostApiPaymobWebhookError = PostApiPaymobWebhookErrors[keyof PostApiPaymobWebhookErrors];

export type PostApiPaymobWebhookResponses = {
    /**
     * OK
     */
    200: PaymentWebhookParseResultResult;
};

export type PostApiPaymobWebhookResponse = PostApiPaymobWebhookResponses[keyof PostApiPaymobWebhookResponses];

export type GetApiProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If true, includes hidden products in the response. Default is false.
         */
        includeHidden?: boolean;
    };
    url: '/api/products';
};

export type GetApiProductsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetApiProductsError = GetApiProductsErrors[keyof GetApiProductsErrors];

export type GetApiProductsResponses = {
    /**
     * OK
     */
    200: ProductDtoListResult;
};

export type GetApiProductsResponse = GetApiProductsResponses[keyof GetApiProductsResponses];

export type PostApiProductsData = {
    /**
     * The details required to create the product.
     */
    body?: CreateProductCommand;
    path?: never;
    query?: never;
    url: '/api/products';
};

export type PostApiProductsErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type PostApiProductsError = PostApiProductsErrors[keyof PostApiProductsErrors];

export type PostApiProductsResponses = {
    /**
     * Created
     */
    201: ProductDtoResult;
};

export type PostApiProductsResponse = PostApiProductsResponses[keyof PostApiProductsResponses];

export type DeleteApiProductsByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product to delete.
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type DeleteApiProductsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiProductsByIdError = DeleteApiProductsByIdErrors[keyof DeleteApiProductsByIdErrors];

export type DeleteApiProductsByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByIdResponse = DeleteApiProductsByIdResponses[keyof DeleteApiProductsByIdResponses];

export type GetApiProductsByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetApiProductsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiProductsByIdError = GetApiProductsByIdErrors[keyof GetApiProductsByIdErrors];

export type GetApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDtoResult;
};

export type GetApiProductsByIdResponse = GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type PutApiProductsByIdData = {
    /**
     * The product details to update.
     */
    body?: UpdateProductCommand;
    path: {
        /**
         * The unique identifier of the product.
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type PutApiProductsByIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiProductsByIdError = PutApiProductsByIdErrors[keyof PutApiProductsByIdErrors];

export type PutApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDtoResult;
};

export type PutApiProductsByIdResponse = PutApiProductsByIdResponses[keyof PutApiProductsByIdResponses];

export type PostApiProductsByParentIdChildrenData = {
    /**
     * The details required to create the child product.
     */
    body?: CreateChildProductRequest;
    path: {
        /**
         * The unique identifier of the parent product.
         */
        parentId: string;
    };
    query?: never;
    url: '/api/products/{parentId}/children';
};

export type PostApiProductsByParentIdChildrenErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type PostApiProductsByParentIdChildrenError = PostApiProductsByParentIdChildrenErrors[keyof PostApiProductsByParentIdChildrenErrors];

export type PostApiProductsByParentIdChildrenResponses = {
    /**
     * Created
     */
    201: ProductDtoResult;
};

export type PostApiProductsByParentIdChildrenResponse = PostApiProductsByParentIdChildrenResponses[keyof PostApiProductsByParentIdChildrenResponses];

export type PostApiProductsByProductIdMediaData = {
    body?: {
        File?: Blob | File;
        Order?: number;
    };
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media';
};

export type PostApiProductsByProductIdMediaErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PostApiProductsByProductIdMediaError = PostApiProductsByProductIdMediaErrors[keyof PostApiProductsByProductIdMediaErrors];

export type PostApiProductsByProductIdMediaResponses = {
    /**
     * Created
     */
    201: ProductMediaDtoResult;
};

export type PostApiProductsByProductIdMediaResponse = PostApiProductsByProductIdMediaResponses[keyof PostApiProductsByProductIdMediaResponses];

export type PostApiProductsByProductIdMediaUrlData = {
    /**
     * The media URL details.
     */
    body?: ProductMediaRequest;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media/url';
};

export type PostApiProductsByProductIdMediaUrlErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PostApiProductsByProductIdMediaUrlError = PostApiProductsByProductIdMediaUrlErrors[keyof PostApiProductsByProductIdMediaUrlErrors];

export type PostApiProductsByProductIdMediaUrlResponses = {
    /**
     * Created
     */
    201: ProductMediaDtoResult;
};

export type PostApiProductsByProductIdMediaUrlResponse = PostApiProductsByProductIdMediaUrlResponses[keyof PostApiProductsByProductIdMediaUrlResponses];

export type DeleteApiProductsByProductIdMediaByMediaIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the media item.
         */
        mediaId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media/{mediaId}';
};

export type DeleteApiProductsByProductIdMediaByMediaIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiProductsByProductIdMediaByMediaIdError = DeleteApiProductsByProductIdMediaByMediaIdErrors[keyof DeleteApiProductsByProductIdMediaByMediaIdErrors];

export type DeleteApiProductsByProductIdMediaByMediaIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByProductIdMediaByMediaIdResponse = DeleteApiProductsByProductIdMediaByMediaIdResponses[keyof DeleteApiProductsByProductIdMediaByMediaIdResponses];

export type PostApiProductsByProductIdFeaturesData = {
    /**
     * The feature details.
     */
    body?: ProductFeatureRequest;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/features';
};

export type PostApiProductsByProductIdFeaturesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PostApiProductsByProductIdFeaturesError = PostApiProductsByProductIdFeaturesErrors[keyof PostApiProductsByProductIdFeaturesErrors];

export type PostApiProductsByProductIdFeaturesResponses = {
    /**
     * Created
     */
    201: ProductFeatureDtoResult;
};

export type PostApiProductsByProductIdFeaturesResponse = PostApiProductsByProductIdFeaturesResponses[keyof PostApiProductsByProductIdFeaturesResponses];

export type DeleteApiProductsByProductIdFeaturesByFeatureIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the feature.
         */
        featureId: string;
    };
    query?: never;
    url: '/api/products/{productId}/features/{featureId}';
};

export type DeleteApiProductsByProductIdFeaturesByFeatureIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiProductsByProductIdFeaturesByFeatureIdError = DeleteApiProductsByProductIdFeaturesByFeatureIdErrors[keyof DeleteApiProductsByProductIdFeaturesByFeatureIdErrors];

export type DeleteApiProductsByProductIdFeaturesByFeatureIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByProductIdFeaturesByFeatureIdResponse = DeleteApiProductsByProductIdFeaturesByFeatureIdResponses[keyof DeleteApiProductsByProductIdFeaturesByFeatureIdResponses];

export type PutApiProductsByProductIdFeaturesByFeatureIdData = {
    /**
     * The feature details to update.
     */
    body?: ProductFeatureRequest;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the feature.
         */
        featureId: string;
    };
    query?: never;
    url: '/api/products/{productId}/features/{featureId}';
};

export type PutApiProductsByProductIdFeaturesByFeatureIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiProductsByProductIdFeaturesByFeatureIdError = PutApiProductsByProductIdFeaturesByFeatureIdErrors[keyof PutApiProductsByProductIdFeaturesByFeatureIdErrors];

export type PutApiProductsByProductIdFeaturesByFeatureIdResponses = {
    /**
     * OK
     */
    200: ProductFeatureDtoResult;
};

export type PutApiProductsByProductIdFeaturesByFeatureIdResponse = PutApiProductsByProductIdFeaturesByFeatureIdResponses[keyof PutApiProductsByProductIdFeaturesByFeatureIdResponses];

export type GetApiPromocodesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If true, includes hidden promocodes in the response. Default is false.
         */
        includeHidden?: boolean;
    };
    url: '/api/promocodes';
};

export type GetApiPromocodesErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetApiPromocodesError = GetApiPromocodesErrors[keyof GetApiPromocodesErrors];

export type GetApiPromocodesResponses = {
    /**
     * OK
     */
    200: PromocodeDtoListResult;
};

export type GetApiPromocodesResponse = GetApiPromocodesResponses[keyof GetApiPromocodesResponses];

export type PostApiPromocodesData = {
    /**
     * The details required to create the promocode (e.g., Code).
     */
    body?: CreatePromocodeCommand;
    path?: never;
    query?: never;
    url: '/api/promocodes';
};

export type PostApiPromocodesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type PostApiPromocodesError = PostApiPromocodesErrors[keyof PostApiPromocodesErrors];

export type PostApiPromocodesResponses = {
    /**
     * Created
     */
    201: PromocodeDtoResult;
};

export type PostApiPromocodesResponse = PostApiPromocodesResponses[keyof PostApiPromocodesResponses];

export type DeleteApiPromocodesByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the promocode to delete.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}';
};

export type DeleteApiPromocodesByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiPromocodesByIdError = DeleteApiPromocodesByIdErrors[keyof DeleteApiPromocodesByIdErrors];

export type DeleteApiPromocodesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiPromocodesByIdResponse = DeleteApiPromocodesByIdResponses[keyof DeleteApiPromocodesByIdResponses];

export type GetApiPromocodesByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the promocode.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}';
};

export type GetApiPromocodesByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiPromocodesByIdError = GetApiPromocodesByIdErrors[keyof GetApiPromocodesByIdErrors];

export type GetApiPromocodesByIdResponses = {
    /**
     * OK
     */
    200: PromocodeDtoResult;
};

export type GetApiPromocodesByIdResponse = GetApiPromocodesByIdResponses[keyof GetApiPromocodesByIdResponses];

export type PutApiPromocodesByIdDiscountsData = {
    /**
     * The discount details to update.
     */
    body?: UpdatePromocodeDiscountsCommand;
    path: {
        /**
         * The unique identifier of the promocode.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}/discounts';
};

export type PutApiPromocodesByIdDiscountsErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiPromocodesByIdDiscountsError = PutApiPromocodesByIdDiscountsErrors[keyof PutApiPromocodesByIdDiscountsErrors];

export type PutApiPromocodesByIdDiscountsResponses = {
    /**
     * OK
     */
    200: PromocodeDtoResult;
};

export type PutApiPromocodesByIdDiscountsResponse = PutApiPromocodesByIdDiscountsResponses[keyof PutApiPromocodesByIdDiscountsResponses];

export type PutApiPromocodesByIdAudienceData = {
    /**
     * The audience targeting details to update.
     */
    body?: UpdatePromocodeAudienceCommand;
    path: {
        /**
         * The unique identifier of the promocode.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}/audience';
};

export type PutApiPromocodesByIdAudienceErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiPromocodesByIdAudienceError = PutApiPromocodesByIdAudienceErrors[keyof PutApiPromocodesByIdAudienceErrors];

export type PutApiPromocodesByIdAudienceResponses = {
    /**
     * OK
     */
    200: PromocodeDtoResult;
};

export type PutApiPromocodesByIdAudienceResponse = PutApiPromocodesByIdAudienceResponses[keyof PutApiPromocodesByIdAudienceResponses];

export type GetApiTicketCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ticket-categories';
};

export type GetApiTicketCategoriesResponses = {
    /**
     * OK
     */
    200: Array<TicketCategoryDto>;
};

export type GetApiTicketCategoriesResponse = GetApiTicketCategoriesResponses[keyof GetApiTicketCategoriesResponses];

export type PostApiTicketCategoriesData = {
    body?: CreateTicketCategoryCommand;
    path?: never;
    query?: never;
    url: '/api/ticket-categories';
};

export type PostApiTicketCategoriesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiTicketCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ticket-categories/{id}';
};

export type DeleteApiTicketCategoriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiTicketCategoriesByIdData = {
    body?: UpdateTicketCategoryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ticket-categories/{id}';
};

export type PutApiTicketCategoriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTicketsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
    };
    url: '/api/tickets';
};

export type GetApiTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTicketsData = {
    body?: CreateTicketRequest;
    path?: never;
    query?: never;
    url: '/api/tickets';
};

export type PostApiTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTicketsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tickets/{id}';
};

export type GetApiTicketsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTicketsByIdCommentsData = {
    body?: AddTicketCommentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tickets/{id}/comments';
};

export type PostApiTicketsByIdCommentsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiTicketsByIdStatusData = {
    body?: UpdateTicketStatusRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tickets/{id}/status';
};

export type PutApiTicketsByIdStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};
